"""Lab generator for creating complete lab exercises."""

import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from cks_lab_generator.config import Config, get_logger
from cks_lab_generator.models import Domain, LabExercise, SkillTopic

logger = get_logger(__name__)


class LabGenerator:
    """Generate complete lab exercises from skill topics."""

    # Mapping from topic ID to English kebab-case name
    TOPIC_NAME_MAP: Dict[str, str] = {
        "1.1": "etcd-encryption",
        "1.2": "network-policy",
        "1.3": "containerd-config",
        "2.1": "api-server-security",
        "2.2": "rbac-least-privilege",
        "2.3": "audit-logging",
        "2.4": "kubelet-security",
        "3.1": "seccomp-profile",
        "3.2": "apparmor-profile",
        "3.3": "linux-capabilities",
        "3.4": "kernel-security-sysctl",
        "4.1": "pod-security-admission",
        "4.2": "trivy-image-scan",
        "4.3": "resource-quota-limitrange",
        "5.1": "cosign-image-signing",
        "5.2": "kyverno-supply-chain",
        "5.3": "image-policy-webhook",
        "5.4": "sbom-syft",
        "6.1": "falco-install",
        "6.2": "falco-custom-rules",
        "6.3": "audit-log-analysis",
        "6.4": "cni-encryption-cilium",
    }

    def __init__(self, config: Config) -> None:
        """Initialize lab generator.

        Args:
            config: Configuration instance
        """
        self.config = config

    def generate_lab(
        self, skill_topic: SkillTopic, domain: Domain, output_dir: Optional[str] = None
    ) -> LabExercise:
        """Generate complete lab exercise.

        Args:
            skill_topic: Skill topic to generate lab for
            domain: Domain the skill topic belongs to
            output_dir: Optional custom output directory

        Returns:
            LabExercise object with all generated content
        """
        logger.info(f"Generating lab for topic {skill_topic.id}: {skill_topic.name}")

        # Determine output directory
        if output_dir is None:
            output_dir = str(self.config.get_output_directory())

        # Create lab directory
        lab_dir = self.create_lab_directory(skill_topic, domain, output_dir)

        # Generate content
        readme_content = self.generate_readme(skill_topic, domain)
        solution_content = self.generate_solution(skill_topic, domain)

        # Create LabExercise object
        lab_id = Path(lab_dir).name
        lab = LabExercise(
            lab_id=lab_id,
            domain_number=domain.number,
            skill_topic=skill_topic,
            directory_path=lab_dir,
            readme_content=readme_content,
            solution_content=solution_content,
            setup_script="",  # Will be generated by ScriptGenerator
            cleanup_script="",  # Will be generated by ScriptGenerator
            verify_script="",  # Will be generated by ScriptGenerator
            created_date=datetime.now().isoformat(),
        )

        # Write files
        self._write_lab_files(lab)

        logger.info(f"Lab generated successfully: {lab_dir}")
        return lab

    def create_lab_directory(
        self, skill_topic: SkillTopic, domain: Domain, output_dir: str
    ) -> str:
        """Create lab directory with proper naming.

        Uses the topic ID directly as the lab number (e.g., topic 1.2 → lab-1.2-...)
        making the operation idempotent - same topic always maps to same directory.

        Args:
            skill_topic: Skill topic for the lab
            domain: Domain the skill topic belongs to
            output_dir: Base output directory

        Returns:
            Path to created lab directory
        """
        # Get domain directory name
        domain_dir_name = f"{domain.number:02d}-{self._to_kebab_case(domain.name)}"
        domain_path = Path(output_dir) / domain_dir_name

        # Create domain directory if it doesn't exist
        domain_path.mkdir(parents=True, exist_ok=True)

        # Use topic ID as lab number (e.g., "1.2" → minor number "2")
        # This makes generation idempotent - same topic always same directory
        topic_parts = skill_topic.id.split(".")
        lab_number = topic_parts[1] if len(topic_parts) > 1 else "1"

        # Use English name from map, fallback to kebab of original name
        topic_kebab = self.TOPIC_NAME_MAP.get(
            skill_topic.id, self._to_kebab_case(skill_topic.name)
        )
        lab_dir_name = f"lab-{domain.number}.{lab_number}-{topic_kebab}"
        lab_path = domain_path / lab_dir_name

        # Create lab directory and solution subdirectory
        lab_path.mkdir(parents=True, exist_ok=True)
        (lab_path / "solution").mkdir(exist_ok=True)

        logger.info(f"Created lab directory: {lab_path}")
        return str(lab_path)

    def _get_next_lab_number(self, domain_path: Path, domain_number: int) -> int:
        """Get next available lab number in domain.

        Args:
            domain_path: Path to domain directory
            domain_number: Domain number

        Returns:
            Next available lab number
        """
        if not domain_path.exists():
            return 1

        # Find all existing lab directories
        existing_labs = []
        pattern = re.compile(rf"lab-{domain_number}\.(\d+)-")

        for item in domain_path.iterdir():
            if item.is_dir() and item.name.startswith("lab-"):
                match = pattern.match(item.name)
                if match:
                    existing_labs.append(int(match.group(1)))

        # Return next number
        if existing_labs:
            return max(existing_labs) + 1
        return 1

    def _to_kebab_case(self, text: str) -> str:
        """Convert text to kebab-case.

        Args:
            text: Text to convert

        Returns:
            Kebab-case string
        """
        # Remove special characters and replace spaces with hyphens
        text = re.sub(r"[^\w\s-]", "", text)
        text = re.sub(r"[\s_]+", "-", text)
        return text.lower().strip("-")

    def generate_readme(self, skill_topic: SkillTopic, domain: Domain) -> str:
        """Generate README.md content.

        Args:
            skill_topic: Skill topic for the lab
            domain: Domain the skill topic belongs to

        Returns:
            README.md content as string
        """
        lines = []

        # Title
        lines.append(f"# Lab {skill_topic.id}: {skill_topic.name}")
        lines.append("")

        # Metadata
        lines.append("## Metadata")
        lines.append("")
        lines.append(f"- **Domain**: {domain.number} - {domain.name}")
        lines.append(f"- **Difficulty**: {skill_topic.difficulty}")
        lines.append(f"- **Estimated Time**: {skill_topic.estimated_time} minutes")
        lines.append(f"- **Exam Weight**: {self.config.get_domain_weight(domain.number)}%")
        lines.append("")

        # Learning Objectives
        lines.append("## Learning Objectives")
        lines.append("")
        if skill_topic.learning_objectives:
            for obj in skill_topic.learning_objectives:
                lines.append(f"- {obj}")
        else:
            # Generate default objectives based on topic
            lines.append(f"- Understand and implement {skill_topic.name}")
            lines.append(f"- Apply security best practices for {skill_topic.name}")
            lines.append(f"- Verify correct configuration of {skill_topic.name}")
        lines.append("")

        # Prerequisites
        lines.append("## Prerequisites")
        lines.append("")
        lines.append("- Kubernetes cluster v1.29+")
        lines.append("- kubectl configured and connected to the cluster")
        if skill_topic.prerequisites:
            for prereq in skill_topic.prerequisites:
                lines.append(f"- {prereq}")
        lines.append("")

        # Scenario
        lines.append("## Scenario")
        lines.append("")
        scenario = self._generate_scenario(skill_topic, domain)
        lines.append(scenario)
        lines.append("")

        # Requirements
        lines.append("## Requirements")
        lines.append("")
        requirements = self._generate_requirements(skill_topic)
        for i, req in enumerate(requirements, 1):
            lines.append(f"{i}. {req}")
        lines.append("")

        # Instructions
        lines.append("## Instructions")
        lines.append("")
        instructions = self._generate_instructions(skill_topic)
        for i, (step_title, step_content) in enumerate(instructions, 1):
            lines.append(f"### Step {i}: {step_title}")
            lines.append("")
            lines.append(step_content)
            lines.append("")

        # Verification
        lines.append("## Verification")
        lines.append("")
        lines.append("Run the verification script to check your solution:")
        lines.append("")
        lines.append("```bash")
        lines.append("./verify.sh")
        lines.append("```")
        lines.append("")
        lines.append("All checks should pass before proceeding.")
        lines.append("")

        # Cleanup
        lines.append("## Cleanup")
        lines.append("")
        lines.append("After completing the lab, clean up the resources:")
        lines.append("")
        lines.append("```bash")
        lines.append("./cleanup.sh")
        lines.append("```")
        lines.append("")

        # Additional Resources
        lines.append("## Additional Resources")
        lines.append("")
        lines.append("- [Kubernetes Documentation](https://kubernetes.io/docs/)")
        lines.append(f"- [CKS Exam Curriculum](https://github.com/cncf/curriculum)")
        lines.append("")

        return "\n".join(lines)

    def _generate_scenario(self, skill_topic: SkillTopic, domain: Domain) -> str:
        """Generate realistic exam-like scenario.

        Args:
            skill_topic: Skill topic for the lab
            domain: Domain the skill topic belongs to

        Returns:
            Scenario description
        """
        # Use context if available
        if skill_topic.context and len(skill_topic.context) > 50:
            # Extract first paragraph as scenario
            paragraphs = skill_topic.context.split("\n\n")
            if paragraphs:
                return paragraphs[0].strip()

        # Generate default scenario based on domain
        scenarios = {
            1: f"Your organization needs to secure the Kubernetes cluster by implementing {skill_topic.name}. "
            f"You have been tasked with configuring this security control to meet compliance requirements.",
            2: f"As part of cluster hardening, you need to configure {skill_topic.name}. "
            f"This is a critical security requirement for production clusters.",
            3: f"The security team requires system-level hardening for all Kubernetes nodes. "
            f"You must implement {skill_topic.name} to reduce the attack surface.",
            4: f"To minimize microservice vulnerabilities, you need to configure {skill_topic.name}. "
            f"This will help prevent common security issues in containerized applications.",
            5: f"Your organization's supply chain security policy requires {skill_topic.name}. "
            f"You must implement this control to ensure only trusted images are deployed.",
            6: f"The security operations team needs runtime monitoring and detection capabilities. "
            f"You are tasked with implementing {skill_topic.name} to detect security threats.",
        }

        return scenarios.get(
            domain.number,
            f"You need to implement {skill_topic.name} as part of Kubernetes security best practices.",
        )

    def _generate_requirements(self, skill_topic: SkillTopic) -> List[str]:
        """Generate lab requirements.

        Args:
            skill_topic: Skill topic for the lab

        Returns:
            List of requirements
        """
        requirements = []

        # Add requirements based on commands and YAML
        if skill_topic.commands:
            requirements.append(
                f"Execute the necessary commands to configure {skill_topic.name}"
            )

        if skill_topic.yaml_manifests:
            requirements.append(
                f"Create and apply the required Kubernetes manifests"
            )

        # Add verification requirement
        requirements.append("Verify the configuration is working correctly")

        # Add documentation requirement for complex labs
        if skill_topic.difficulty == "Hard":
            requirements.append(
                "Document any troubleshooting steps you performed"
            )

        return requirements

    def _generate_instructions(
        self, skill_topic: SkillTopic
    ) -> List[tuple[str, str]]:
        """Generate step-by-step instructions.

        Args:
            skill_topic: Skill topic for the lab

        Returns:
            List of (step_title, step_content) tuples
        """
        instructions = []

        # Step 1: Setup
        instructions.append(
            (
                "Set up the lab environment",
                "Run the setup script to create the initial resources:\n\n"
                "```bash\n./setup.sh\n```\n\n"
                "This will create the necessary namespace and base resources.",
            )
        )

        # Step 2: Main task based on topic
        main_task = self._generate_main_task(skill_topic)
        instructions.append(("Complete the main task", main_task))

        # Step 3: Verification
        instructions.append(
            (
                "Verify your solution",
                "Use the verification script to check if your configuration is correct:\n\n"
                "```bash\n./verify.sh\n```\n\n"
                "Review any failed checks and make corrections as needed.",
            )
        )

        return instructions

    def _generate_main_task(self, skill_topic: SkillTopic) -> str:
        """Generate main task description.

        Args:
            skill_topic: Skill topic for the lab

        Returns:
            Main task description
        """
        task_parts = []

        # Add context if available
        if skill_topic.context:
            # Extract relevant parts of context
            context_lines = skill_topic.context.split("\n")
            relevant_context = [
                line for line in context_lines if line.strip() and not line.startswith("#")
            ][:3]
            if relevant_context:
                task_parts.append("\n".join(relevant_context))
                task_parts.append("")

        # Add command examples if available
        if skill_topic.commands:
            task_parts.append("Execute the following commands:")
            task_parts.append("")
            for cmd in skill_topic.commands[:3]:  # Limit to first 3 commands
                task_parts.append(f"```bash\n{cmd.command}\n```")
                if cmd.description:
                    task_parts.append(f"*{cmd.description}*")
                task_parts.append("")

        # Add YAML examples if available
        if skill_topic.yaml_manifests:
            task_parts.append("Create and apply the following Kubernetes resources:")
            task_parts.append("")
            for manifest in skill_topic.yaml_manifests[:2]:  # Limit to first 2
                task_parts.append(f"```yaml\n{manifest.content}\n```")
                if manifest.description:
                    task_parts.append(f"*{manifest.description}*")
                task_parts.append("")

        # Default task if no specific content
        if not task_parts:
            task_parts.append(
                f"Configure {skill_topic.name} according to Kubernetes security best practices."
            )
            task_parts.append("")
            task_parts.append(
                "Refer to the official Kubernetes documentation for detailed configuration options."
            )

        return "\n".join(task_parts)

    def generate_solution(self, skill_topic: SkillTopic, domain: Domain) -> str:
        """Generate solution.md content.

        Args:
            skill_topic: Skill topic for the lab
            domain: Domain the skill topic belongs to

        Returns:
            solution.md content as string
        """
        lines = []

        # Title
        lines.append(f"# Solution: Lab {skill_topic.id} - {skill_topic.name}")
        lines.append("")

        # Overview
        lines.append("## Overview")
        lines.append("")
        lines.append(
            f"This solution provides step-by-step instructions for completing the "
            f"{skill_topic.name} lab exercise."
        )
        lines.append("")

        # Solution Steps
        lines.append("## Solution Steps")
        lines.append("")

        # Generate solution steps
        solution_steps = self._generate_solution_steps(skill_topic)
        for i, (step_title, step_content) in enumerate(solution_steps, 1):
            lines.append(f"### Step {i}: {step_title}")
            lines.append("")
            lines.append(step_content)
            lines.append("")

        # Verification
        lines.append("## Verification")
        lines.append("")
        lines.append("After completing all steps, verify your solution:")
        lines.append("")
        lines.append("```bash")
        lines.append("./verify.sh")
        lines.append("```")
        lines.append("")
        lines.append("Expected output: All checks should pass.")
        lines.append("")

        # Common Mistakes
        lines.append("## Common Mistakes")
        lines.append("")
        mistakes = self._generate_common_mistakes(skill_topic)
        for mistake in mistakes:
            lines.append(f"- {mistake}")
        lines.append("")

        # Troubleshooting
        lines.append("## Troubleshooting")
        lines.append("")
        troubleshooting = self._generate_troubleshooting(skill_topic)
        for issue, solution in troubleshooting:
            lines.append(f"**Issue**: {issue}")
            lines.append("")
            lines.append(f"**Solution**: {solution}")
            lines.append("")

        # Key Takeaways
        lines.append("## Key Takeaways")
        lines.append("")
        takeaways = self._generate_key_takeaways(skill_topic)
        for takeaway in takeaways:
            lines.append(f"- {takeaway}")
        lines.append("")

        return "\n".join(lines)

    def _generate_solution_steps(
        self, skill_topic: SkillTopic
    ) -> List[tuple[str, str]]:
        """Generate solution steps.

        Args:
            skill_topic: Skill topic for the lab

        Returns:
            List of (step_title, step_content) tuples
        """
        steps = []

        # Step 1: Run setup
        steps.append(
            (
                "Run the setup script",
                "Execute the setup script to create the initial environment:\n\n"
                "```bash\n./setup.sh\n```",
            )
        )

        # Add steps based on commands
        if skill_topic.commands:
            for i, cmd in enumerate(skill_topic.commands, 2):
                title = cmd.description or f"Execute command {i - 1}"
                content = f"```bash\n{cmd.command}\n```"
                if cmd.description:
                    content += f"\n\n{cmd.description}"
                steps.append((title, content))

        # Add steps based on YAML manifests
        if skill_topic.yaml_manifests:
            for i, manifest in enumerate(skill_topic.yaml_manifests):
                step_num = len(steps) + 1
                title = manifest.description or f"Apply {manifest.resource_type}"
                content = f"Create a file with the following content:\n\n```yaml\n{manifest.content}\n```\n\n"
                content += "Apply the manifest:\n\n```bash\nkubectl apply -f <filename>\n```"
                steps.append((title, content))

        # Final verification step
        steps.append(
            (
                "Verify the configuration",
                "Run the verification script to confirm everything is working:\n\n"
                "```bash\n./verify.sh\n```",
            )
        )

        return steps

    def _generate_common_mistakes(self, skill_topic: SkillTopic) -> List[str]:
        """Generate common mistakes list.

        Args:
            skill_topic: Skill topic for the lab

        Returns:
            List of common mistakes
        """
        mistakes = [
            "Forgetting to create the namespace before applying resources",
            "Not waiting for resources to be ready before verification",
            "Incorrect YAML indentation",
        ]

        # Add difficulty-specific mistakes
        if skill_topic.difficulty == "Hard":
            mistakes.extend(
                [
                    "Missing required labels or annotations",
                    "Incorrect security context configuration",
                    "Not considering resource dependencies",
                ]
            )

        return mistakes

    def _generate_troubleshooting(
        self, skill_topic: SkillTopic
    ) -> List[tuple[str, str]]:
        """Generate troubleshooting tips.

        Args:
            skill_topic: Skill topic for the lab

        Returns:
            List of (issue, solution) tuples
        """
        tips = [
            (
                "Resources not being created",
                "Check kubectl logs and describe the resources to see error messages. "
                "Verify YAML syntax and API versions.",
            ),
            (
                "Verification script fails",
                "Review the specific check that failed. Use kubectl get/describe commands "
                "to inspect the actual state of resources.",
            ),
        ]

        return tips

    def _generate_key_takeaways(self, skill_topic: SkillTopic) -> List[str]:
        """Generate key takeaways.

        Args:
            skill_topic: Skill topic for the lab

        Returns:
            List of key takeaways
        """
        takeaways = [
            f"Understanding {skill_topic.name} is essential for Kubernetes security",
            "Always verify configurations before deploying to production",
            "Security controls should be tested regularly",
        ]

        return takeaways

    def _write_lab_files(self, lab: LabExercise) -> None:
        """Write lab files to disk.

        Args:
            lab: LabExercise object with content to write
        """
        lab_path = Path(lab.directory_path)

        # Write README.md
        readme_path = lab_path / "README.md"
        readme_path.write_text(lab.readme_content, encoding="utf-8")
        logger.info(f"Created README.md: {readme_path}")

        # Write solution.md
        solution_path = lab_path / "solution" / "solution.md"
        solution_path.write_text(lab.solution_content, encoding="utf-8")
        logger.info(f"Created solution.md: {solution_path}")

        # Create placeholder scripts (will be replaced by ScriptGenerator)
        for script_name in ["setup.sh", "cleanup.sh", "verify.sh"]:
            script_path = lab_path / script_name
            if not script_path.exists():
                script_path.write_text(
                    f"#!/bin/bash\n# TODO: Implement {script_name}\n",
                    encoding="utf-8",
                )
                script_path.chmod(0o755)
                logger.info(f"Created placeholder {script_name}: {script_path}")

    def assign_difficulty(self, skill_topic: SkillTopic) -> str:
        """Determine difficulty level.

        Args:
            skill_topic: Skill topic to assess

        Returns:
            Difficulty level: "Easy", "Medium", or "Hard"
        """
        # If already assigned, return it
        if skill_topic.difficulty:
            return skill_topic.difficulty

        # Calculate complexity score
        num_commands = len(skill_topic.commands)
        num_yaml = len(skill_topic.yaml_manifests)
        num_prereqs = len(skill_topic.prerequisites)

        # Get criteria from config
        easy_criteria = self.config.get_difficulty_criteria("easy")
        medium_criteria = self.config.get_difficulty_criteria("medium")

        # Determine difficulty
        if (
            num_commands <= easy_criteria["max_commands"]
            and num_yaml <= easy_criteria["max_yaml_files"]
        ):
            return "Easy"
        elif (
            num_commands <= medium_criteria["max_commands"]
            and num_yaml <= medium_criteria["max_yaml_files"]
        ):
            return "Medium"
        else:
            return "Hard"

    def estimate_time(self, skill_topic: SkillTopic) -> int:
        """Estimate completion time in minutes.

        Args:
            skill_topic: Skill topic to estimate

        Returns:
            Estimated time in minutes
        """
        # If already estimated, return it
        if skill_topic.estimated_time:
            return skill_topic.estimated_time

        # Base time
        base_time = 5

        # Add time based on complexity
        time = base_time
        time += len(skill_topic.commands) * 1  # 1 min per command
        time += len(skill_topic.yaml_manifests) * 2  # 2 min per YAML
        time += len(skill_topic.prerequisites) * 2  # 2 min per prerequisite

        # Adjust for difficulty
        difficulty = self.assign_difficulty(skill_topic)
        if difficulty == "Hard":
            time = int(time * 1.5)
        elif difficulty == "Medium":
            time = int(time * 1.2)

        return time

    def update_main_readme(
        self, lab: LabExercise, main_readme_path: str
    ) -> None:
        """Update main README.md with new lab entry.

        Args:
            lab: LabExercise to add to README
            main_readme_path: Path to main README.md
        """
        readme_path = Path(main_readme_path)

        if not readme_path.exists():
            logger.warning(f"Main README not found: {main_readme_path}")
            return

        # Read existing content
        content = readme_path.read_text(encoding="utf-8")

        # Find domain section
        domain_header = f"## Domain {lab.domain_number}"
        if domain_header not in content:
            logger.warning(f"Domain section not found in README: {domain_header}")
            return

        # Create lab entry
        lab_entry = f"| {lab.lab_id} | {lab.topic_name} | {lab.skill_topic.difficulty} |\n"

        # Find insertion point (after domain table header)
        lines = content.split("\n")
        insert_index = -1

        for i, line in enumerate(lines):
            if line.startswith(domain_header):
                # Find table header
                for j in range(i, min(i + 10, len(lines))):
                    if lines[j].startswith("|") and "Lab" in lines[j]:
                        # Found table, insert after separator line
                        insert_index = j + 2
                        break
                break

        if insert_index > 0:
            lines.insert(insert_index, lab_entry.rstrip())
            updated_content = "\n".join(lines)
            readme_path.write_text(updated_content, encoding="utf-8")
            logger.info(f"Updated main README: {main_readme_path}")
        else:
            logger.warning("Could not find insertion point in README")

    def batch_generate(
        self,
        skill_topics: List[SkillTopic],
        domains: Dict[int, Domain],
        output_dir: Optional[str] = None,
    ) -> tuple[List[LabExercise], List[tuple[SkillTopic, str]]]:
        """Generate multiple labs in batch.

        Args:
            skill_topics: List of skill topics to generate labs for
            domains: Dictionary mapping domain numbers to Domain objects
            output_dir: Optional custom output directory

        Returns:
            Tuple of (successful_labs, failed_labs_with_errors)
        """
        logger.info(f"Starting batch generation of {len(skill_topics)} labs")

        successful = []
        failed = []

        for topic in skill_topics:
            try:
                # Get domain for this topic
                domain = domains.get(topic.domain_number)
                if not domain:
                    raise ValueError(f"Domain {topic.domain_number} not found")

                # Generate lab
                lab = self.generate_lab(topic, domain, output_dir)
                successful.append(lab)

            except Exception as e:
                logger.error(f"Failed to generate lab for {topic.id}: {e}")
                failed.append((topic, str(e)))

        logger.info(
            f"Batch generation complete: {len(successful)} successful, {len(failed)} failed"
        )

        return successful, failed
